# Generated by Django 6.0.5 on 2026-05-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_borrar',
            field=models.BooleanField(default=False, help_text='Permite eliminar registros'),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_editar',
            field=models.BooleanField(default=False, help_text='Permite crear y modificar registros'),
        ),
        migrations.AddField(
            model_name='rol',
            name='puede_ver',
            field=models.BooleanField(default=True, help_text='Permite ver listados y detalles'),
        ),
    ]
