# Generated by Django 6.0.5 on 2026-05-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rol_puede_borrar_rol_puede_editar_rol_puede_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='puede_ver',
            field=models.BooleanField(default=False, help_text='Permite ver listados y detalles'),
        ),
    ]
