# Generated by Django 6.0.5 on 2026-05-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rol_puede_ver'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_configurar',
            field=models.BooleanField(default=False, help_text='Permite cambiar ajustes de sesión y globales'),
        ),
    ]
