# Generated by Django 6.0.5 on 2026-05-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('cantidad_rollizos', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('espesor_pulgadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho_pulgadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo_pies', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_piezas', models.IntegerField(default=0)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.materiaprima')),
            ],
        ),
    ]
